version: '3.8'

services:
  vulnerable-shop:
    build: .
    container_name: vulnerable-shop
    privileged: true
    ports:
      - "3000:3000"
      - "8080:8080"
      - "22:22"
      - "9229:9229"
      - "5432:5432"
      - "3306:3306"
      - "6379:6379"
      - "27017:27017"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=super-secret-key-123
      - JWT_EXPIRES_IN=30d
      - ADMIN_EMAIL=admin@shop.com
      - ADMIN_PASSWORD=password123
      - UPLOAD_PATH=/app/uploads
      - MAX_FILE_SIZE=104857600
      - PAYMENT_WEBHOOK_SECRET=webhook-secret-123
      - THIRD_PARTY_API_KEY=sk-12345abcdef67890
      - ALLOWED_ORIGINS=*
      - RATE_LIMIT_ENABLED=false
      - LOG_LEVEL=debug
      - LOG_SENSITIVE_DATA=true
      - AWS_ACCESS_KEY_ID=AKIA123456789EXAMPLE
      - AWS_SECRET_ACCESS_KEY=abcd1234efgh5678ijkl9012mnop3456qrst7890
      - DOCKER_REGISTRY_PASSWORD=dockerhub123
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
      - .:/app:rw
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_MODULE
      - DAC_OVERRIDE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    network_mode: host
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    user: "0:0"

  vulnerable-db:
    image: postgres:13
    container_name: vulnerable-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=vulnerable_shop
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  vulnerable-redis:
    image: redis:6
    container_name: vulnerable-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "" --protected-mode no
    volumes:
      - ./redis_data:/data

  vulnerable-monitor:
    image: prom/prometheus
    container_name: vulnerable-monitor
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'

  vulnerable-files:
    image: nginx:alpine
    container_name: vulnerable-files
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
